/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

import static com.sun.webkit.graphics.WCImage.getImage;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JLabel;

/**
 *
 * @author Juan Pablo
 */
public class Inicio extends javax.swing.JFrame {
        NodoMantenimiento nodom;
        NodoColaPasajeros nodocp;
        ListaAvion lista = new ListaAvion();
        NodoAvion nodoa = new NodoAvion();
        NodoEquipaje nodoe;
        ColaMantenimiento cola = new ColaMantenimiento();
        ColaPasajeros colap = new ColaPasajeros();
        ColaPasajeros col=new ColaPasajeros();
        ColaPasajeros col1=new ColaPasajeros();
        ColaPasajeros col2=new ColaPasajeros();
        ColaPasajeros col3=new ColaPasajeros();
        ListaPersona persona = new ListaPersona();
        NodoPersona nodop = new NodoPersona();
        ListaEquipaje maleta = new ListaEquipaje();
        NodoPersona guardar = new NodoPersona();
        NodoColaMantenimiento cola1 = new NodoColaMantenimiento();
        public NodoAvion aux; 
        ListaMantenimiento listam = new ListaMantenimiento();
        ListaEscritorios listae = new ListaEscritorios();
        Random rm = new Random();
        int turno=1,i,type,pasajeros,desabordaje,mantenimiento,k,L,q,h,s,pasajeroa,pasajeron,maletaa,maletan;
        String tipo;
        int p,m,e1=0,e2=e1+5,maletas,documentos,Tregistro;
        Enviar enviar = new Enviar();
       // Graficador graficador = new Graficador();
        NodoColaPasajeros aux1=new NodoColaPasajeros();
        NodoPersona aux11 = new NodoPersona();
        
        
        
        
        
        
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("5");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("AVIONES:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("ESTACIONES:");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("1");

        jButton1.setText("EMPEZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel3.setText("AVIONES:");

        jButton2.setText("Pasar Turno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("ESCRITORIOS");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("2");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jButton4.setText("Cola Desabordaje Pasajeros");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane5.setViewportView(jLabel7);

        jButton5.setText("ListaAviones Desabordaje");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Mantenimiento");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Maletas");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Todo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Escritorios");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel5.setText("Graficar: ");

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel6.setText("ESCRITORIOS:");

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel8.setText("MALETAS: ");

        jLabel9.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel9.setText("PASAJEROS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jButton3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jButton1)
                                .addGap(36, 36, 36)
                                .addComponent(jButton2)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addComponent(jTextField3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(69, 69, 69)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(37, 37, 37)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton3)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Aviones
        if (turno==1){    
        jTextArea1.append("-------------------------Aviones-------------------------"+'\n');
        jTextArea1.append("Turno: "+turno+'\n');
        
        type=rm.nextInt(3);
      // type=2;
            switch(type){
                case 0: 
                tipo="Pequenio";
                        do {
                        pasajeros=rm.nextInt(11);
                        } while (pasajeros<5);
                        //en la variable p se guardan los pasajeros anteriores
                        pasajeron=pasajeros;
                        
                            desabordaje=1;
                        do {
                            mantenimiento=rm.nextInt(4);
                        } while(mantenimiento==0); 
                        lista.insertarFinal(turno,tipo,pasajeros,desabordaje,mantenimiento);
                      break;
                      
                case 1: tipo = "Mediano";
                        do {
                        pasajeros=rm.nextInt(26);
                        } while (pasajeros<15);
                        pasajeron=pasajeros;
                            desabordaje=2;
                        do {
                            mantenimiento=rm.nextInt(5);
                        } while(mantenimiento<2); 
                        lista.insertarFinal(turno,tipo,pasajeros,desabordaje,mantenimiento);
                      break;
                      
                
                case 2: tipo ="Grande";  
                        do {
                        pasajeros=rm.nextInt(41);
                        } while (pasajeros<30);
                        pasajeron=pasajeros;
                            desabordaje=3;
                        do {
                            mantenimiento=rm.nextInt(7);
                        } while(mantenimiento<3); 
                        lista.insertarFinal(turno,tipo,pasajeros,desabordaje,mantenimiento);
                      break;
                      
                
            }
        
        
        //turno+=1;
        lista.recorrer(jTextArea1);
        
        
        //Pasajeros
        for (i=1;i<=pasajeron;i++){
            do{
            maletas=rm.nextInt(5);
            }while(maletas==0);
            //maletas=1;
            //Sumando las maletas de todos los pasajeros. En k se guardan las maletas anteriores
            maletan=maletan+maletas;
            do{
                documentos=rm.nextInt(11);
            }while(documentos==0);
            
            do{
                Tregistro=rm.nextInt(4);
            }while(Tregistro==0);
            persona.insertarFinal(i, maletas,documentos,Tregistro);
            
        }
        jTextArea2.append(" "+'\n');
        jTextArea2.append("---------------------------Escritorios--------------------"+'\n');
        jTextArea2.append("Turno: "+turno+'\n');
        for (int i = 1; i <=Integer.parseInt(jTextField3.getText()) ; i++) {
            listae.insertarFinal(0, 0, 0, i, 0, 0,0);
            
        }
        
       
       
        
        
        
        jTextArea4.append(" "+'\n');
        jTextArea4.append("------------------------Pasajeros----------------------"+'\n');
        jTextArea4.append("Turno: "+turno+'\n');
        persona.Pcola(listae);
        persona.recorrer(jTextArea4);
       listae.recorrer(jTextArea2); 
        //Cola y Escritorios
        
        
        
        
        

        
        
        
        jTextArea3.append(" "+'\n');
        jTextArea3.append("-------------------------Maletas--------------------------"+'\n');
       jTextArea3.append("Turno: "+turno+'\n');
        //se va a crear cada una de las maletas
        for (i=1;i<=maletan;i++){
        maleta.insertarFinal(i);
        }
        maleta.recorrer(jTextArea3);
        
        
        
        //Mantenimiento
        
        jTextArea1.append(" "+'\n');
        jTextArea1.append("--------------------Mantenimiento--------------------"+'\n');
        jTextArea1.append("Turno: "+turno+'\n');
        for (int i = 1; i <=Integer.parseInt(jTextField2.getText()) ; i++) {
            listam.insertarFinal(i,0, 0, " ", 0, 0, 0);
            
        }
       
       listam.recorrer(jTextArea1);
       //cola.descolar(mantenimiento, listam);
        
        //la variable m va a guardar los pasajeros viejos
        
        //m guarda los pasajeros anteriores
        pasajeroa=pasajeron;
        //h guarda las maletas anteriores
        maletaa=maletan+1;
        // no se que have
        q=maletan+1;
        
        
        }else{
            jButton1.disable();
        }
        cola.primero=null;
        turno+=1;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel7.setIcon(null);
       jTextArea1.append(" "+'\n');
        jTextArea1.append(" "+'\n');    
        jTextArea1.append("-------------------------Aviones-------------------------"+'\n');
        jTextArea1.append("Turno: "+turno+'\n'); 
       
        
 
        if(turno<=Integer.parseInt(jTextField1.getText())){
      
        
        type=rm.nextInt(3);
        //type=0;    
        switch(type){
                case 0: 
                tipo="Pequenio";
                        do {
                        pasajeros=rm.nextInt(11);
                        } while (pasajeros<5);
                        pasajeron+=pasajeros;
                            desabordaje=2;
                        do {
                            mantenimiento=rm.nextInt(4);
                        } while(mantenimiento==0||mantenimiento==1); 
                        lista.insertarFinal(turno,tipo,pasajeros,desabordaje,mantenimiento);
                      break;
                      
                case 1: tipo = "Mediano";
                        do {
                        pasajeros=rm.nextInt(26);
                        } while (pasajeros<15);
                        pasajeron+=pasajeros; 
                        desabordaje=3;
                        do {
                            mantenimiento=rm.nextInt(5);
                        } while(mantenimiento<2); 
                        lista.insertarFinal(turno,tipo,pasajeros,desabordaje,mantenimiento);
                      break;
                      
                
                case 2: tipo ="Grande";  
                        do {
                        pasajeros=rm.nextInt(41);
                        } while (pasajeros<30);
                        pasajeron+=pasajeros;
                        desabordaje=4;
                        do {
                            mantenimiento=rm.nextInt(7);
                        } while(mantenimiento<3); 
                        lista.insertarFinal(turno,tipo,pasajeros,desabordaje,mantenimiento);
                      break;
                      
                
            }
            
                
                
            
        }else{
            
        }
        
        lista.restarTurno(turno);
        for(int i=0;i<=turno;i++){
        lista.eliminar(lista,cola,Integer.parseInt(jTextField2.getText()),listam);
        }
        
       
                    if (lista.primero!=null){
                        lista.recorrer(jTextArea1);
                    }
                
        
       //Pasajeros
        //Guardando las maletas de los pasajeros
        //para i pasajeros anteriores hasta i pasajeros nuevos
        for (i=pasajeroa+1;i<=pasajeron;i++){
            do{
            maletas=rm.nextInt(5);
            }while(maletas==0);
            //maletas=1;
            //Se suman todas las variables de los pasajeros
            maletan=maletan+maletas;
           
            do{
                documentos=rm.nextInt(11);
            }while(documentos==0);
            do{
                Tregistro=rm.nextInt(4);
            }while(Tregistro==0);
            persona.insertarFinal(i, maletas,documentos,Tregistro);
        }
        
        jTextArea4.append(" "+'\n');
        jTextArea4.append("------------------------Pasajeros----------------------"+'\n');
        jTextArea4.append("Turno: "+turno+'\n');
        //persona.Pcola(colap);
         
        
        
        
        
        
        
        
        
        
        jTextArea2.append("---------------------------Escritorios--------------------"+'\n');
        jTextArea2.append("Turno: "+turno+'\n');
       listae.restarTurno();
       for(int i=0;i<=turno;i++){
        listae.eliminar(maleta);
        }
       persona.Pcola(listae);
       listae.recorrer(jTextArea2);
       persona.recorrer(jTextArea4); 
        
        
        
                
         //Maletas
         
        jTextArea3.append(" "+'\n');
        jTextArea3.append("-------------------------Maletas--------------------------"+'\n');
        jTextArea3.append("Turno: "+turno+'\n');
        for (i=maletaa;i<maletan;i++){
            maleta.insertarFinal(q);
            q+=1;
        }
        
                
        
        maleta.recorrer(jTextArea3);
        
                
                
        //Cola
        jTextArea1.append(" "+'\n');
        jTextArea1.append(" "+'\n');    
        jTextArea1.append("---------------------------Cola---------------------------"+'\n');
        jTextArea1.append("Turno: "+turno+'\n'); 
        if(cola.primero!=null){
        
        for(int i = 1 ; i<=Integer.parseInt(jTextField2.getText()) ; i++){
        cola.descolar1(listam);
        }
        }
        
        
        cola.imprimir(jTextArea1);
        
        
        maletaa=maletan+1;
        pasajeroa=pasajeron+1;
        q=q+1;
        
        
        
            /*try {
                //Mantenimiento
                listam.sustituir(Integer.parseInt(jTextField2.getText()));
            } catch (ListaMantenimiento.ExceptionListaVacia ex) {
                //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        jTextArea1.append(" "+'\n');
        jTextArea1.append("--------------------Mantenimiento--------------------"+'\n');
        jTextArea1.append("Turno: "+turno+'\n');
       listam.recorrer(jTextArea1);
       listam.restarTurno(turno);
       listam.eliminar(lista, cola, mantenimiento, listam);
       
       
                
           
        turno+=1;        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       JOptionPane.showMessageDialog(null,maleta.primero.getMaletas());
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for(int k =1 ; k<=3;k++){
        GraficadorCPD graficador = new GraficadorCPD();    
        try {
                // TODO add your handling code here:

                graficador.Graficar(persona,graficador);
            } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        ImageIcon imagen = new ImageIcon("Grafica.png");
        imagen.getImage().hashCode();
       imagen.getImage().flush(); // ¡LÍNEA CLAVE!
        jLabel7.repaint();
        jLabel7.setIcon(imagen);
        jLabel7.repaint();
        
    }
       
       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       for(int i=1; i<=3;i++){
        GraficadorLAD graficador = new GraficadorLAD();    
        try {
                

                graficador.Graficar(lista,graficador);
            } catch (IOException ex) {
                //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        ImageIcon imagen = new ImageIcon("Grafica.png");
        
       imagen.getImage().flush(); 
       
        jLabel7.setIcon(imagen);
        jLabel7.validate();
        jLabel7.updateUI();
        jLabel7.updateUI();
        jLabel7.updateUI();
        jLabel7.updateUI();
        jLabel7.validate();
        jLabel7.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(cola.primero!=null){
        
        GraficadorM graficador = new GraficadorM();    
        try {
                // TODO add your handling code here:

                graficador.Graficar(listam,cola,graficador);
            } catch (IOException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        ImageIcon imagen = new ImageIcon("Grafica.png");
        imagen.getImage().hashCode();
       imagen.getImage().flush(); // ¡LÍNEA CLAVE!
        jLabel7.repaint();
        jLabel7.setIcon(imagen);
        jLabel7.repaint();
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        GrafoMal grafo = new GrafoMal();
            try {
                grafo.Graficar(maleta, grafo);
            } catch (IOException ex) {
                //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        ImageIcon imagen = new ImageIcon("Grafica.png");
        imagen.getImage().hashCode();
       imagen.getImage().flush(); // ¡LÍNEA CLAVE!
        jLabel7.repaint();
        jLabel7.setIcon(imagen);
        jLabel7.repaint();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    GraficarTodo grafo = new GraficarTodo();
            try {
                grafo.Graficar(listam, cola, persona, maleta, lista,listae, grafo); //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        ImageIcon imagen = new ImageIcon("Grafica.png");
        imagen.getImage().hashCode();
       imagen.getImage().flush(); // ¡LÍNEA CLAVE!
        jLabel7.repaint();
        jLabel7.setIcon(imagen);
        jLabel7.repaint();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      GraficadorCE grafo = new GraficadorCE();
            try {
                grafo.Graficar(listae, grafo); //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                //Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        ImageIcon imagen = new ImageIcon("Grafica.png");
        imagen.getImage().hashCode();
       imagen.getImage().flush(); // ¡LÍNEA CLAVE!
        jLabel7.repaint();
        jLabel7.setIcon(imagen);
        jLabel7.repaint();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
